version: "3"
services:

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - db

  db:
    image: mysql:5.7.36
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: scraper
      TZ: America/Sao_Paulo
      LANG: C.UTF-8
    expose:
      - '3306'
    logging:
      driver: none
    volumes:
      - ./build/mysql-init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", '/usr/bin/mysql --user=root --password=1234 --execute "SHOW DATABASE;"' ]
      interval: 10s
      timeout: 2s
      retries: 10