version: "3"
services:

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: America/Sao_Paulo
      LANG: C.UTF-8
    expose:
      - '3306'
    volumes:
      - ./build/mysql-init:/docker-entrypoint-initdb.d
    logging:
      driver: none
    restart: always