// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/product/usecase.go

// Package product_mock is a generated GoMock package.
package product_mock

import (
	product "product-scraping/pkg/domain/product"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// ParseProductURL mocks base method.
func (m *MockUseCase) ParseProductURL(url string) (*product.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseProductURL", url)
	ret0, _ := ret[0].(*product.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseProductURL indicates an expected call of ParseProductURL.
func (mr *MockUseCaseMockRecorder) ParseProductURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseProductURL", reflect.TypeOf((*MockUseCase)(nil).ParseProductURL), url)
}
